export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

// test
export const GETDATALIST = 'GETDATALIST';
export type GETDATALIST = typeof GETDATALIST;

// header
export const SENDHEADERINFO = 'SENDHEADERINFO';
export type SENDHEADERINFO = typeof SENDHEADERINFO;

export const GETTEST = 'GETTEST'
export type GETTEST = typeof GETTEST;